name: myblog
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: mhkz/blog@master
      env:
        ACCESS_TOKEN: ${{ secrets.myblog }}
        BRANCH: master
        FOLDER: .vuepress/dist
        BUILD_SCRIPT: npm install && npm run build